INSERT INTO CMS_USERS(NAME, TEAMNAME, SALARY) VALUES('Jack','EFO',100);
INSERT INTO CMS_USERS(NAME, TEAMNAME, SALARY) VALUES('Tim','EFO',110);
INSERT INTO CMS_USERS(NAME, TEAMNAME, SALARY) VALUES('Anna','LF',120);